### ISSUE TITLE
Don't impersonate user with CloudClient

### ISSUE THREAD

**Issue by psylinse** [GetStream/stream-java#82]
I'm using the CloudClient in an Android application. When I try to add something to a user's feed I get "Don't impersonate user" with this code:

```kotlin
        client = CloudClient
            .builder(credentials.apiKey, credentials.token, "jeff")
            .build()
        val feed = client.flatFeed("user")
        feed.addActivity(
            Activity
                .builder()
                .actor("jeff")
                .verb("post")
                .`object`(UUID.randomUUID().toString())
                .extraField("message", message)
                .build()
        ).join()
```

However, it seems to work fine if I prefix the user with `SU:` like so:

```kotlin
        client = CloudClient
            .builder(credentials.apiKey, credentials.token, "jeff")
            .build()
        val feed = client.flatFeed("user")
        feed.addActivity(
            Activity
                .builder()
                .actor("SU:jeff")
                .verb("post")
                .`object`(UUID.randomUUID().toString())
                .extraField("message", message)
                .build()
        ).join()
```

With the other libraries (Swift/JS/etc.) I don't have to do this. Am I doing something wrong? What's the significance of `SU`?

Thanks!

**Comment by ferhatelmas** [comment]
@psylinse Sorry, it seems this issue is missed.

`SU:` makes it an enrichable user object stored in our side (in long form **S**tream **U**ser)

You see this error because you initialized your client with a user (`jeff`) and 
with default permission, jeff can only push activities to `user:jeff` and to ensure it, backend needs its id. However, you could store regular strings there too so we needed a special prefix to differentiate if it is a regular string or a user id. It's a bit unfortunate, this detail is exposed to user in this SDK, slightly because you don't have a user object but its id.
