### ISSUE TITLE
Commons-codec Issue in Android Devices

### ISSUE THREAD

**Issue by AlexDelosSantos** [GetStream/stream-java#89]
The library is using JWT library that uses features of apache **commons-codec** that is only available in version **1.4** and higher, the problem is android runtime has a built in commons-codec that will always be used in runtime which is version **1.3**. Therefore result to method "**java.lang.NoSuchMethodError: No static method**" error due to those features are not available yet in version **1.3** of **commons codec**.

gz#6908

**Comment by ferhatelmas** [comment]
Seems this issue is deeper, let me see what we can do.

**Comment by ferhatelmas** [comment]
@AlexDelosSantos Are you using `client.Client` in android ? If so, use `cloud.CloudClient`.

**Comment by AlexDelosSantos** [comment]
> @AlexDelosSantos Are you using `client.Client` in android ? If so, use `cloud.CloudClient`.

Thank you for answering. I Tried using the cloudclient, but the cloud client requires the generated token, and token generation also requires the commons-codec 1.4 and up.

**Comment by AlexDelosSantos** [comment]
Also feeds docs is not yet available for android Kotlin, only the chat API. 
![image](https://user-images.githubusercontent.com/10624148/97516109-621d2780-19cd-11eb-9b24-2a678e13a1e7.png)

**Comment by ferhatelmas** [comment]
> I Tried using the cloudclient, but the cloud client requires the generated token, and token generation also requires the commons-codec 1.4 and up.

Ok, clear. You need to generate the token in your server which is supposed to be [not an android runtime](https://github.com/auth0/java-jwt/issues/131#issuecomment-270947116).
Codec won't be an issue because cloud client will get the token from your backend and will pass to our backend, it doesn't need to do any signing which is causing the issue.

Yes, kotlin might come for feeds in the future but not available at the moment.
